### ISSUE TITLE
How can I get the content file?

### ISSUE THREAD

**Issue by rochapablo** [joltup/react-native-fetch-blob#59]
Using `react-native-document-picker` I'm getting the file and trying do upload to my api. So I would like to know how can I read the file, convert to do base64 and send it.

This is how I'm trying to read the file, but i always return only the path, not the content.

```
// const file = base64.encode(RNFetchBlob.fs.asset(filename))
// const file = base64.encode(filename)
// const file = await RNFetchBlob.fs.readFile(filename, 'base64')
// const file = base64.encode(await RNFetchBlob.fs.readFile(filename, 'binary'))

const { fs, fetch, wrap } = RNFetchBlob
const file = fs.asset(filename)
```

```
bundle-assets://content://com.android.providers.downloads.documents/document/431/pexels-photo-267151.jpeg
```

Wha could I be missing?

```
"base-64": "^0.1.0",
"react-native": "^0.48.4",
"react-native-fetch-blob": "^0.10.8",
"react-native-document-picker": "^2.1.0",
```

**Comment by rochapablo** [comment]
Working with `DocumentPicker` + `RNFetchBlob` did the job.

**Comment by shubhnik** [comment]
Hi @rochapablo , I am facing maybe a similar issue. Can you please have a look at this issue #79 . Let me know if more info is needed, thanks :)

**Comment by mohasu1992** [comment]
is this issue resolved or not!!!

**Comment by fukemy** [comment]
NOT
