### ISSUE TITLE
error: duplicate declaration of method 'requiresMainQueueSetup'

### ISSUE THREAD

**Issue by jnrepo** [joltup/react-native-fetch-blob#64]
On version 0.10.9, `requiresMainQueueSetup` is declared twice in this file and will throw the error 
```
error: duplicate declaration of method 'requiresMainQueueSetup'
```

Seems this was introduced on the latest commit for 0.10.9 branch.
https://github.com/joltup/react-native-fetch-blob/commit/614ef561dda7b837e896e175f8719fb42232bede#diff-0b97a2df65bc9a2753599b4d88da3475R45

Lines in question:

https://github.com/joltup/react-native-fetch-blob/blob/614ef561dda7b837e896e175f8719fb42232bede/ios/RNFetchBlob/RNFetchBlob.m#L45

https://github.com/joltup/react-native-fetch-blob/blob/614ef561dda7b837e896e175f8719fb42232bede/ios/RNFetchBlob/RNFetchBlob.m#L77

**Comment by Traviskn** [comment]
Thanks for the issue, should now be fixed on the 0.10.9 branch
