### ISSUE TITLE
Read file in node_modules

### ISSUE THREAD

**Issue by amsdamsgram** [joltup/react-native-fetch-blob#71]
Hi,

I'm trying to read a file from node_modules to be able to inject it to a webview.
But I am not able to get the right path from `fs.readFile()` to access node_modules.

I tried a relative or absolute path but it is not working:
```
RNFetchBlob.fs
      .readFile("./node_modules/epubjs/dist/epub.min.js", "utf8")
      .then(data => { // handle data })
```
```
RNFetchBlob.fs
      .readFile(__dirname + "/node_modules/epubjs/dist/epub.min.js", "utf8")
      .then(data => { // handle data })
```

RN: 0.55.4
RNFetchBlob: 0.10.8

Thanks!

**Comment by ssedrick** [comment]
`node_modules` does not exist on the device. It is on you computer.
You will need to move `epub.min.js` into the apps assets folder (on android `app/resources`, not sure for iOS) to get the file onto the device.
Once you have the file in the assets, you will want to use the following:
```
RNFetchBlob.fs.readFile("file:///path/to/assets/epub.min.js", "utf8").then(...)
```

**Comment by amsdamsgram** [comment]
Thanks @ssedrick I'll try this.

**Comment by amsdamsgram** [comment]
It works thanks!

I've dragged my file to the root project on Xcode, then restarted Xcode.
I have now access to the file with the following path: `RNFetchBlob.fs.dirs.MainBundleDir + "/MY_FILENAME";`

**Comment by fukemy** [comment]
plz help i got this error:
error [Error: No such file '/Users/vedax/Library/Developer/CoreSimulator/Devices/B54DFF22-FCB3-4171-9040-8CE76D8F6CC1/data/Containers/Bundle/Application/B8A3C336-FAF5-43DD-B59E-0F088E29C7FA/VedaxLink.app/dx.material.blue.light.css']

```
const filename = 'dx.material.blue.light.css'
        let path = `${fs.dirs.MainBundleDir}/${filename}`
        console.log('path', path)
        fs.readFile(path, "utf8").then(data => {
            
        }).catch(error => [
            console.log('error', error)
        ])
```
