### ISSUE TITLE
Android: error: package okhttp3 does not exist import okhttp3.MediaType;

### ISSUE THREAD

**Issue by sinewave440hz** [joltup/react-native-fetch-blob#72]
My android build is failing with this error.

/node_modules/react-native-fetch-blob/android/src/main/java/com/RNFetchBlob/Response/RNFetchBlobDefaultResp.java:14: error: package okhttp3 does not exist
import okhttp3.MediaType;

Environment:
  OS:  macOS Sierra 10.12.6
  Node:  8.1.4
  Yarn:  1.7.0
  npm:  5.8.0
  Watchman:  4.7.0
  Xcode:  Xcode 9.2 Build version 9C40b
  Android Studio:  2.3 AI-162.4069837

Packages: (wanted => installed)
  react: 16.3.0 => 16.3.0
  react-native: 0.54.4 => 0.54.4

"react-native-fetch-blob": "^0.10.8",

How do I get this building again? Thanks!

**Comment by sinewave440hz** [comment]
Turns out that this project was missing 
```
maven {
            // All of React Native (JS, Obj-C sources, Android binaries) is installed from npm
            url "$rootDir/../node_modules/react-native/android"
        }
```

which makes this a non-issue ;)

**Comment by majidln** [comment]
same
